### PR TITLE
Start the v3 documentation

### PR DESCRIPTION
**Pull request by shyrat**

### CODE REVIEW

**Comment by tomlandia** [comment]
Thanks a lot!!! messages/conversations endpoints should require no payload but it'd be super useful if you could look into sending pics or setting your own and especially creating the GCM token with google if possible so I can start implementing without setting up a phone and MITM setup.

**Comment by shyrat** [comment]
I did look at how the GCM token is created.  It involves trading a device ID that was presumably created earlier when the OS was installed... I don't feel too comfortable about faking that.  I'm curious what happens on iOS.  Google does have a GCM SDK for iOS, but it obviously isn't native, so maybe it's less integrated?

On a related note, I noticed that v2 and v3 session IDs are interchangeable.  So you can log in with a v2 flow, and start making v3 API calls.  That makes migration easier.

Also, do you have anything set up to MITM the XMPP side of things?  I have less experience there.

**Comment by tomlandia** [comment]
Thanks a lot for the session ID tip. There must be a request to some Google/ex-Firebase server; this connection might use proper certificate pinning though :/. Nope, we could Wireshark/TShark but XMPP hasn't changed much and you can see the other side in the terminal if you speak between Fuckr and Grindr. Can you just add chat/profile pics or should I merge and complete?

**Comment by shyrat** [comment]
Google doesn't use any pinning, as far as I can tell.  I added a section on photo upload.

**Comment by tomlandia** [comment]
Thanks 👍, I'll assume chat pics are the same endpoint. Well all we'll need is Grindr's app key which is probably in all GCM requests.

**Comment by shyrat** [comment]
Chat pics are already documented in there :)

**Comment by ZeroFeetAway** [comment]
Any idea what is kind of token is being generated for iPhone users or do they use GCM for both?

**Comment by JKalash** [comment]
@ZeroFeetAway did you figure it out?

**Comment by ZeroFeetAway** [comment]
@JKalash, nope. I still don't know what request is being made in order to obtain the token for iPhone users. It looks much different than the GCM token last I looked.

**Comment by JKalash** [comment]
@ZeroFeetAway Yeah. The token being used is extremely short. Digits only. Makes me wonder what it is.

**Pull request merged**
