### PR TITLE
Improvements on Filtering

### PR DESCRIPTION
**Pull request by victorgrego**
- Created personalized filters for each of the fields in the profile.
- Added the capability of filtering by 3 different criteria;
- Added a new filter helper in the local storage;
- Changed the profile layout, enlarged the table, allowing the insertion
of all elements present in the profile.

### CODE REVIEW

**Comment by genevera** [comment]
:+1:

**Comment by genevera** [comment]
One thing, though.  You don't need to (and shouldn't!) hardcode the id=>text mapping for relationship status/tribes/etc.  All of that is delivered by the server via the managedFields call (https://github.com/tomlandia/fuckr/blob/master/unofficial-grindr-api-documentation.md#managed-fields).  If Grindr changes the mappings, it'll make things get weird quick for users :).

**Comment by victorgrego** [comment]
I tried to used the automatic fields with a plugin, but had no success, I can improve this in future releases, as this is kinda temporary. Moreover, while debbugging I found that grindr sometimes return values out of the range that is handled (idk the reason) so i think it would be nice to have a manual filter.

**Comment by lucianRf** [comment]
I wanted to rn this one as it has the updated features and hasn't been merged, but I can't seem to get it to work. Running nw . only produces an nw.exe with the black background / menu buttons but nothing is functional. Any ideas how to fix this?

**Comment by tomlandia** [comment]
Sorry to close but:

1. I can't merge changes in `fuckr.js` as I'd have to get rid of CoffeeScript and the file structure to keep them (there are already merge conflicts).
2. Most profiles don't have these frivolous attributes. I'm still reluctant to add these filters to Fuckr.

**Comment by genevera** [comment]
Most profiles don't utilize these attributes?  You couldn't possibly be serious? Grindr would be next to unusable for many people (like this woman of trans experience) if it weren't for the ability to filter profiles by tribes etc. That's why I use a vm on my laptop rather than this and I would much rather support you and other LGBT devs writing cool things like this client.

**Comment by tomlandia** [comment]
Sorry didn't know. It's in [v 1.6.0](https://github.com/tomlandia/fuckr/releases/1.6.0) (filtering only, not displayed on profiles).

**Pull request closed without merging**
